'use server';

/**
 * @fileOverview A flow to improve project descriptions using AI.
 *
 * - improveProjectDescription - A function that improves a project description.
 * - ImproveProjectDescriptionInput - The input type for the improveProjectDescription function.
 * - ImproveProjectDescriptionOutput - The return type for the improveProjectDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveProjectDescriptionInputSchema = z.object({
  description: z
    .string()
    .describe('The original project description that needs improvement.'),
});
export type ImproveProjectDescriptionInput = z.infer<
  typeof ImproveProjectDescriptionInputSchema
>;

const ImproveProjectDescriptionOutputSchema = z.object({
  improvedDescription: z
    .string()
    .describe('The improved project description generated by the AI.'),
});
export type ImproveProjectDescriptionOutput = z.infer<
  typeof ImproveProjectDescriptionOutputSchema
>;

export async function improveProjectDescription(
  input: ImproveProjectDescriptionInput
): Promise<ImproveProjectDescriptionOutput> {
  return improveProjectDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveProjectDescriptionPrompt',
  input: {schema: ImproveProjectDescriptionInputSchema},
  output: {schema: ImproveProjectDescriptionOutputSchema},
  prompt: `You are an AI-powered tool that improves project descriptions to effectively showcase contributions and skills.

  Original Description: {{{description}}}

  Improved Description:`, // The AI will generate the improved description here
});

const improveProjectDescriptionFlow = ai.defineFlow(
  {
    name: 'improveProjectDescriptionFlow',
    inputSchema: ImproveProjectDescriptionInputSchema,
    outputSchema: ImproveProjectDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
