
import type { EditorThemeClasses } from 'lexical';

export const editorTheme: EditorThemeClasses = {
  ltr: 'text-left',
  rtl: 'text-right',
  paragraph: 'mb-2',
  quote: 'my-2 mx-0 pl-4 border-l-4 border-muted text-muted-foreground',
  heading: {
    h1: 'text-4xl font-bold my-4',
    h2: 'text-3xl font-bold my-3',
    h3: 'text-2xl font-bold my-2',
    h4: 'text-xl font-bold my-1',
    h5: 'text-lg font-bold',
  },
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'list-decimal list-inside my-2',
    ul: 'list-disc list-inside my-2',
    listitem: 'ml-4',
  },
  link: 'text-primary underline',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-muted p-1 rounded-sm font-mono text-sm',
  },
  code: 'bg-muted p-4 rounded-md font-mono text-sm block my-2 overflow-x-auto',
  codeHighlight: {
    atrule: 'text-sky-500',
    attr: 'text-sky-500',
    boolean: 'text-purple-500',
    builtin: 'text-teal-500',
    cdata: 'text-gray-500',
    char: 'text-green-500',
    class: 'text-orange-500',
    'class-name': 'text-orange-500',
    comment: 'text-gray-500',
    constant: 'text-purple-500',
    deleted: 'text-red-500',
    doctype: 'text-gray-500',
    entity: 'text-red-500',
    function: 'text-yellow-500',
    important: 'text-red-500',
    inserted: 'text-green-500',
    keyword: 'text-sky-500',
    namespace: 'text-teal-500',
    number: 'text-purple-500',
    operator: 'text-sky-500',
    prolog: 'text-gray-500',
    property: 'text-red-500',
    punctuation: 'text-gray-500',
    regex: 'text-yellow-500',
    selector: 'text-green-500',
    string: 'text-green-500',
    symbol: 'text-purple-500',
    tag: 'text-red-500',
    url: 'text-red-500',
    variable: 'text-orange-500',
  },
};
